### ISSUE TITLE
Erreur a la connexion si pas de festivals dans la BDD

### ISSUE THREAD

**Issue by XioNoX** [XioNoX/Benevolus#11]
Benevolus devait afficher un message d'erreur et rediriger l’utilisateur vers créer festival si il est admin.

**Comment by jrm2k6** [comment]
I'm on it!
Presque fini selon moi.

**Comment by XioNoX** [comment]
Solved with commit 4a24112d20134e77164c36b4e49e9d3cc114e7d7 from Jérémy!
